### ISSUE TITLE
Login buttons still exist when already logged in

### ISSUE THREAD

**Issue by DrewMcArthur** [whtwnd/whitewind-blog#14]
<img width="227" alt="Screenshot 2024-07-22 at 8 39 27 PM" src="https://github.com/user-attachments/assets/062d4454-85e2-468f-bdc4-27935461fad8">

I'd expect to only see the "sign out" button once I've logged in. 

i'll open a PR that fixes this shortly, this seems like a good introduction to the codebase :) 

great project, thanks for your work on it!

**Comment by K-Nksm** [comment]
The reasoning is detailed in https://github.com/whtwnd/whitewind-blog/pull/15#issuecomment-2424003125
