### ISSUE TITLE
Feature request: Footnotes

### ISSUE THREAD

**Issue by makoConstruct** [whtwnd/whitewind-blog#65]
They're nice whenever there's more to say about something but you want to let the reader choose whether to go and read it, a common occurrence.

Recommend taking inspiration from [the greatest and only analytic philosophy forum/community blog](https://www.lesswrong.com/posts/bF353RHmuzFQcsokF/cohabitive-games-so-far), they do this thing where if you have enough horizontal screen space, the footnotes show on the side (an aside: the table of content shows on the left. It's great), and of course footnotes also pop up on hover.

There are extension standards concerning footnotes in markdown but I don't know if they're good. Implementations I've seen don't allow the user to put anything after the footnote section even though everyone at first expects that to be allowed and it would be easy to implement.

**Comment by makoConstruct** [comment]
![Screenshot_20241125-144133_Vivaldi](https://github.com/user-attachments/assets/66e26005-3a67-4379-b2ca-3979a5645789)

Also consider taking inspiration from Gwern's site, We're clicking footnotes on mobile at first creates a popover instead of moving the view all the way to the bottom of the page which is disorienting.

**Comment by bumblefudge** [comment]
https://whtwnd.com/did:plc:53ogl5ixuq44t73wuqawpa33/3lcmwd6d5pb2g

Seems like markdown footnotes (`[^1]` in the text, `[^1]: ` at the bottom) seem to work already? I would vote for:

stick to vanilla markdown style > embellish presentation of markdown with fancy CSS > make a custom thing

Mostly because I want to be able to cut-and-paste each post into my personal markdown-based blog on my own domain anyways 😄

**Comment by K-Nksm** [comment]
Thank you, Markdown's default footnote notation should work!

**Comment by makoConstruct** [comment]
Ah, I guess I was confused, I think I tried to use the standard markdown syntax and got the impression it wasn't working, no idea why sorry.

Hmm, I'm not totally sure whether allowing content after footnotes would break compatability with the current standard (footnotes are not in the vanilla standard btw). I think it depends on whether there are people who like to write the footnotes inline right after they used them, instead of putting them all at the bottom of the markdown file, EG

```markdown
He confessed that his claimed desire to stay had been a velleity[^1] in light of the war. There was no way to know if he'd meant it.

[^1]: Velleity: A desire too weak to be actionable.

He would leave regardless. The children were able to accept that the front needed him more.
```

If people do that, then the current behaviour shouldn't be changed.
