### ISSUE TITLE
did:web accounts give "Invalid DID"

### ISSUE THREAD

**Issue by leo60228** [whtwnd/whitewind-blog#81]
This seems to be a result of https://github.com/whtwnd/whitewind-blog/blob/4574e587e6d27051a14ea35e4be6bdbb22466e85/frontend/src/services/validator.ts#L42 looking for a `"did"` field instead of the correct `"id"`. Making a duplicate field in the DID document under that name works around the issue.

**Comment by K-Nksm** [comment]
Thank you for reporting an issue!
The cause and fix were very clear.
Fixed!
